// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/capability/v1beta1/capability.proto

package cosmos.capability.v1beta1;

public final class CapabilityOuterClass {
  private CapabilityOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CapabilityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.capability.v1beta1.Capability)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 index = 1 [(.gogoproto.moretags) = "yaml:&#92;"index&#92;""];</code>
     * @return The index.
     */
    long getIndex();
  }
  /**
   * <pre>
   * Capability defines an implementation of an object capability. The index
   * provided to a Capability must be globally unique.
   * </pre>
   *
   * Protobuf type {@code cosmos.capability.v1beta1.Capability}
   */
  public static final class Capability extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.capability.v1beta1.Capability)
      CapabilityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Capability.newBuilder() to construct.
    private Capability(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Capability() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Capability();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Capability(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              index_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_Capability_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_Capability_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Capability.class, Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private long index_;
    /**
     * <code>uint64 index = 1 [(.gogoproto.moretags) = "yaml:&#92;"index&#92;""];</code>
     * @return The index.
     */
    @Override
    public long getIndex() {
      return index_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0L) {
        output.writeUInt64(1, index_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, index_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Capability)) {
        return super.equals(obj);
      }
      Capability other = (Capability) obj;

      if (getIndex()
          != other.getIndex()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIndex());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Capability parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Capability parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Capability parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Capability parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Capability parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Capability parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Capability parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Capability parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Capability parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Capability parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Capability parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Capability parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Capability prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Capability defines an implementation of an object capability. The index
     * provided to a Capability must be globally unique.
     * </pre>
     *
     * Protobuf type {@code cosmos.capability.v1beta1.Capability}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.capability.v1beta1.Capability)
        CapabilityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_Capability_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_Capability_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Capability.class, Builder.class);
      }

      // Construct using cosmos.capability.v1beta1.CapabilityOuterClass.Capability.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        index_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_Capability_descriptor;
      }

      @Override
      public Capability getDefaultInstanceForType() {
        return Capability.getDefaultInstance();
      }

      @Override
      public Capability build() {
        Capability result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Capability buildPartial() {
        Capability result = new Capability(this);
        result.index_ = index_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Capability) {
          return mergeFrom((Capability)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Capability other) {
        if (other == Capability.getDefaultInstance()) return this;
        if (other.getIndex() != 0L) {
          setIndex(other.getIndex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Capability parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Capability) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long index_ ;
      /**
       * <code>uint64 index = 1 [(.gogoproto.moretags) = "yaml:&#92;"index&#92;""];</code>
       * @return The index.
       */
      @Override
      public long getIndex() {
        return index_;
      }
      /**
       * <code>uint64 index = 1 [(.gogoproto.moretags) = "yaml:&#92;"index&#92;""];</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(long value) {

        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 index = 1 [(.gogoproto.moretags) = "yaml:&#92;"index&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {

        index_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.capability.v1beta1.Capability)
    }

    // @@protoc_insertion_point(class_scope:cosmos.capability.v1beta1.Capability)
    private static final Capability DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Capability();
    }

    public static Capability getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Capability>
        PARSER = new com.google.protobuf.AbstractParser<Capability>() {
      @Override
      public Capability parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Capability(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Capability> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Capability> getParserForType() {
      return PARSER;
    }

    @Override
    public Capability getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OwnerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.capability.v1beta1.Owner)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string module = 1 [(.gogoproto.moretags) = "yaml:&#92;"module&#92;""];</code>
     * @return The module.
     */
    String getModule();
    /**
     * <code>string module = 1 [(.gogoproto.moretags) = "yaml:&#92;"module&#92;""];</code>
     * @return The bytes for module.
     */
    com.google.protobuf.ByteString
        getModuleBytes();

    /**
     * <code>string name = 2 [(.gogoproto.moretags) = "yaml:&#92;"name&#92;""];</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 2 [(.gogoproto.moretags) = "yaml:&#92;"name&#92;""];</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * <pre>
   * Owner defines a single capability owner. An owner is defined by the name of
   * capability and the module name.
   * </pre>
   *
   * Protobuf type {@code cosmos.capability.v1beta1.Owner}
   */
  public static final class Owner extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.capability.v1beta1.Owner)
      OwnerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Owner.newBuilder() to construct.
    private Owner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Owner() {
      module_ = "";
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Owner();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Owner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              module_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_Owner_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_Owner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Owner.class, Builder.class);
    }

    public static final int MODULE_FIELD_NUMBER = 1;
    private volatile Object module_;
    /**
     * <code>string module = 1 [(.gogoproto.moretags) = "yaml:&#92;"module&#92;""];</code>
     * @return The module.
     */
    @Override
    public String getModule() {
      Object ref = module_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        module_ = s;
        return s;
      }
    }
    /**
     * <code>string module = 1 [(.gogoproto.moretags) = "yaml:&#92;"module&#92;""];</code>
     * @return The bytes for module.
     */
    @Override
    public com.google.protobuf.ByteString
        getModuleBytes() {
      Object ref = module_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        module_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2 [(.gogoproto.moretags) = "yaml:&#92;"name&#92;""];</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2 [(.gogoproto.moretags) = "yaml:&#92;"name&#92;""];</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(module_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, module_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(module_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, module_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Owner)) {
        return super.equals(obj);
      }
      Owner other = (Owner) obj;

      if (!getModule()
          .equals(other.getModule())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MODULE_FIELD_NUMBER;
      hash = (53 * hash) + getModule().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Owner parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Owner parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Owner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Owner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Owner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Owner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Owner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Owner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Owner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Owner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Owner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Owner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Owner prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Owner defines a single capability owner. An owner is defined by the name of
     * capability and the module name.
     * </pre>
     *
     * Protobuf type {@code cosmos.capability.v1beta1.Owner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.capability.v1beta1.Owner)
        OwnerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_Owner_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_Owner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Owner.class, Builder.class);
      }

      // Construct using cosmos.capability.v1beta1.CapabilityOuterClass.Owner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        module_ = "";

        name_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_Owner_descriptor;
      }

      @Override
      public Owner getDefaultInstanceForType() {
        return Owner.getDefaultInstance();
      }

      @Override
      public Owner build() {
        Owner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Owner buildPartial() {
        Owner result = new Owner(this);
        result.module_ = module_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Owner) {
          return mergeFrom((Owner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Owner other) {
        if (other == Owner.getDefaultInstance()) return this;
        if (!other.getModule().isEmpty()) {
          module_ = other.module_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Owner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Owner) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object module_ = "";
      /**
       * <code>string module = 1 [(.gogoproto.moretags) = "yaml:&#92;"module&#92;""];</code>
       * @return The module.
       */
      public String getModule() {
        Object ref = module_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          module_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string module = 1 [(.gogoproto.moretags) = "yaml:&#92;"module&#92;""];</code>
       * @return The bytes for module.
       */
      public com.google.protobuf.ByteString
          getModuleBytes() {
        Object ref = module_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          module_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string module = 1 [(.gogoproto.moretags) = "yaml:&#92;"module&#92;""];</code>
       * @param value The module to set.
       * @return This builder for chaining.
       */
      public Builder setModule(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        module_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string module = 1 [(.gogoproto.moretags) = "yaml:&#92;"module&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearModule() {

        module_ = getDefaultInstance().getModule();
        onChanged();
        return this;
      }
      /**
       * <code>string module = 1 [(.gogoproto.moretags) = "yaml:&#92;"module&#92;""];</code>
       * @param value The bytes for module to set.
       * @return This builder for chaining.
       */
      public Builder setModuleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        module_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2 [(.gogoproto.moretags) = "yaml:&#92;"name&#92;""];</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2 [(.gogoproto.moretags) = "yaml:&#92;"name&#92;""];</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2 [(.gogoproto.moretags) = "yaml:&#92;"name&#92;""];</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2 [(.gogoproto.moretags) = "yaml:&#92;"name&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2 [(.gogoproto.moretags) = "yaml:&#92;"name&#92;""];</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.capability.v1beta1.Owner)
    }

    // @@protoc_insertion_point(class_scope:cosmos.capability.v1beta1.Owner)
    private static final Owner DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Owner();
    }

    public static Owner getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Owner>
        PARSER = new com.google.protobuf.AbstractParser<Owner>() {
      @Override
      public Owner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Owner(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Owner> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Owner> getParserForType() {
      return PARSER;
    }

    @Override
    public Owner getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CapabilityOwnersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.capability.v1beta1.CapabilityOwners)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<Owner>
        getOwnersList();
    /**
     * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
     */
    Owner getOwners(int index);
    /**
     * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
     */
    int getOwnersCount();
    /**
     * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<? extends OwnerOrBuilder>
        getOwnersOrBuilderList();
    /**
     * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
     */
    OwnerOrBuilder getOwnersOrBuilder(
        int index);
  }
  /**
   * <pre>
   * CapabilityOwners defines a set of owners of a single Capability. The set of
   * owners must be unique.
   * </pre>
   *
   * Protobuf type {@code cosmos.capability.v1beta1.CapabilityOwners}
   */
  public static final class CapabilityOwners extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.capability.v1beta1.CapabilityOwners)
      CapabilityOwnersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CapabilityOwners.newBuilder() to construct.
    private CapabilityOwners(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CapabilityOwners() {
      owners_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CapabilityOwners();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CapabilityOwners(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                owners_ = new java.util.ArrayList<Owner>();
                mutable_bitField0_ |= 0x00000001;
              }
              owners_.add(
                  input.readMessage(Owner.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          owners_ = java.util.Collections.unmodifiableList(owners_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_CapabilityOwners_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_CapabilityOwners_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CapabilityOwners.class, Builder.class);
    }

    public static final int OWNERS_FIELD_NUMBER = 1;
    private java.util.List<Owner> owners_;
    /**
     * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
     */
    @Override
    public java.util.List<Owner> getOwnersList() {
      return owners_;
    }
    /**
     * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
     */
    @Override
    public java.util.List<? extends OwnerOrBuilder>
        getOwnersOrBuilderList() {
      return owners_;
    }
    /**
     * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
     */
    @Override
    public int getOwnersCount() {
      return owners_.size();
    }
    /**
     * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
     */
    @Override
    public Owner getOwners(int index) {
      return owners_.get(index);
    }
    /**
     * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
     */
    @Override
    public OwnerOrBuilder getOwnersOrBuilder(
        int index) {
      return owners_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < owners_.size(); i++) {
        output.writeMessage(1, owners_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < owners_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, owners_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CapabilityOwners)) {
        return super.equals(obj);
      }
      CapabilityOwners other = (CapabilityOwners) obj;

      if (!getOwnersList()
          .equals(other.getOwnersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOwnersCount() > 0) {
        hash = (37 * hash) + OWNERS_FIELD_NUMBER;
        hash = (53 * hash) + getOwnersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CapabilityOwners parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CapabilityOwners parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CapabilityOwners parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CapabilityOwners parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CapabilityOwners parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CapabilityOwners parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CapabilityOwners parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CapabilityOwners parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CapabilityOwners parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CapabilityOwners parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CapabilityOwners parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CapabilityOwners parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CapabilityOwners prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * CapabilityOwners defines a set of owners of a single Capability. The set of
     * owners must be unique.
     * </pre>
     *
     * Protobuf type {@code cosmos.capability.v1beta1.CapabilityOwners}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.capability.v1beta1.CapabilityOwners)
        CapabilityOwnersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_CapabilityOwners_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_CapabilityOwners_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CapabilityOwners.class, Builder.class);
      }

      // Construct using cosmos.capability.v1beta1.CapabilityOuterClass.CapabilityOwners.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOwnersFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (ownersBuilder_ == null) {
          owners_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ownersBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CapabilityOuterClass.internal_static_cosmos_capability_v1beta1_CapabilityOwners_descriptor;
      }

      @Override
      public CapabilityOwners getDefaultInstanceForType() {
        return CapabilityOwners.getDefaultInstance();
      }

      @Override
      public CapabilityOwners build() {
        CapabilityOwners result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CapabilityOwners buildPartial() {
        CapabilityOwners result = new CapabilityOwners(this);
        int from_bitField0_ = bitField0_;
        if (ownersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            owners_ = java.util.Collections.unmodifiableList(owners_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.owners_ = owners_;
        } else {
          result.owners_ = ownersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CapabilityOwners) {
          return mergeFrom((CapabilityOwners)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CapabilityOwners other) {
        if (other == CapabilityOwners.getDefaultInstance()) return this;
        if (ownersBuilder_ == null) {
          if (!other.owners_.isEmpty()) {
            if (owners_.isEmpty()) {
              owners_ = other.owners_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOwnersIsMutable();
              owners_.addAll(other.owners_);
            }
            onChanged();
          }
        } else {
          if (!other.owners_.isEmpty()) {
            if (ownersBuilder_.isEmpty()) {
              ownersBuilder_.dispose();
              ownersBuilder_ = null;
              owners_ = other.owners_;
              bitField0_ = (bitField0_ & ~0x00000001);
              ownersBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOwnersFieldBuilder() : null;
            } else {
              ownersBuilder_.addAllMessages(other.owners_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CapabilityOwners parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CapabilityOwners) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Owner> owners_ =
        java.util.Collections.emptyList();
      private void ensureOwnersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          owners_ = new java.util.ArrayList<Owner>(owners_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Owner, Owner.Builder, OwnerOrBuilder> ownersBuilder_;

      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<Owner> getOwnersList() {
        if (ownersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(owners_);
        } else {
          return ownersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public int getOwnersCount() {
        if (ownersBuilder_ == null) {
          return owners_.size();
        } else {
          return ownersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Owner getOwners(int index) {
        if (ownersBuilder_ == null) {
          return owners_.get(index);
        } else {
          return ownersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setOwners(
          int index, Owner value) {
        if (ownersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOwnersIsMutable();
          owners_.set(index, value);
          onChanged();
        } else {
          ownersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setOwners(
          int index, Owner.Builder builderForValue) {
        if (ownersBuilder_ == null) {
          ensureOwnersIsMutable();
          owners_.set(index, builderForValue.build());
          onChanged();
        } else {
          ownersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addOwners(Owner value) {
        if (ownersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOwnersIsMutable();
          owners_.add(value);
          onChanged();
        } else {
          ownersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addOwners(
          int index, Owner value) {
        if (ownersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOwnersIsMutable();
          owners_.add(index, value);
          onChanged();
        } else {
          ownersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addOwners(
          Owner.Builder builderForValue) {
        if (ownersBuilder_ == null) {
          ensureOwnersIsMutable();
          owners_.add(builderForValue.build());
          onChanged();
        } else {
          ownersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addOwners(
          int index, Owner.Builder builderForValue) {
        if (ownersBuilder_ == null) {
          ensureOwnersIsMutable();
          owners_.add(index, builderForValue.build());
          onChanged();
        } else {
          ownersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addAllOwners(
          Iterable<? extends Owner> values) {
        if (ownersBuilder_ == null) {
          ensureOwnersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, owners_);
          onChanged();
        } else {
          ownersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearOwners() {
        if (ownersBuilder_ == null) {
          owners_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          ownersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder removeOwners(int index) {
        if (ownersBuilder_ == null) {
          ensureOwnersIsMutable();
          owners_.remove(index);
          onChanged();
        } else {
          ownersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Owner.Builder getOwnersBuilder(
          int index) {
        return getOwnersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public OwnerOrBuilder getOwnersOrBuilder(
          int index) {
        if (ownersBuilder_ == null) {
          return owners_.get(index);  } else {
          return ownersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<? extends OwnerOrBuilder>
           getOwnersOrBuilderList() {
        if (ownersBuilder_ != null) {
          return ownersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(owners_);
        }
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Owner.Builder addOwnersBuilder() {
        return getOwnersFieldBuilder().addBuilder(
            Owner.getDefaultInstance());
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Owner.Builder addOwnersBuilder(
          int index) {
        return getOwnersFieldBuilder().addBuilder(
            index, Owner.getDefaultInstance());
      }
      /**
       * <code>repeated .cosmos.capability.v1beta1.Owner owners = 1 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<Owner.Builder>
           getOwnersBuilderList() {
        return getOwnersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Owner, Owner.Builder, OwnerOrBuilder>
          getOwnersFieldBuilder() {
        if (ownersBuilder_ == null) {
          ownersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Owner, Owner.Builder, OwnerOrBuilder>(
                  owners_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          owners_ = null;
        }
        return ownersBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.capability.v1beta1.CapabilityOwners)
    }

    // @@protoc_insertion_point(class_scope:cosmos.capability.v1beta1.CapabilityOwners)
    private static final CapabilityOwners DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CapabilityOwners();
    }

    public static CapabilityOwners getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CapabilityOwners>
        PARSER = new com.google.protobuf.AbstractParser<CapabilityOwners>() {
      @Override
      public CapabilityOwners parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CapabilityOwners(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CapabilityOwners> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CapabilityOwners> getParserForType() {
      return PARSER;
    }

    @Override
    public CapabilityOwners getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_capability_v1beta1_Capability_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_capability_v1beta1_Capability_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_capability_v1beta1_Owner_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_capability_v1beta1_Owner_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_capability_v1beta1_CapabilityOwners_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_capability_v1beta1_CapabilityOwners_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n*cosmos/capability/v1beta1/capability.p" +
      "roto\022\031cosmos.capability.v1beta1\032\024gogopro" +
      "to/gogo.proto\"3\n\nCapability\022\037\n\005index\030\001 \001" +
      "(\004B\020\362\336\037\014yaml:\"index\":\004\230\240\037\000\"S\n\005Owner\022!\n\006m" +
      "odule\030\001 \001(\tB\021\362\336\037\ryaml:\"module\"\022\035\n\004name\030\002" +
      " \001(\tB\017\362\336\037\013yaml:\"name\":\010\230\240\037\000\210\240\037\000\"J\n\020Capab" +
      "ilityOwners\0226\n\006owners\030\001 \003(\0132 .cosmos.cap" +
      "ability.v1beta1.OwnerB\004\310\336\037\000B1Z/github.co" +
      "m/cosmos/cosmos-sdk/x/capability/typesb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_cosmos_capability_v1beta1_Capability_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cosmos_capability_v1beta1_Capability_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_capability_v1beta1_Capability_descriptor,
        new String[] { "Index", });
    internal_static_cosmos_capability_v1beta1_Owner_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cosmos_capability_v1beta1_Owner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_capability_v1beta1_Owner_descriptor,
        new String[] { "Module", "Name", });
    internal_static_cosmos_capability_v1beta1_CapabilityOwners_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cosmos_capability_v1beta1_CapabilityOwners_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_capability_v1beta1_CapabilityOwners_descriptor,
        new String[] { "Owners", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.goprotoGetters);
    registry.add(com.google.protobuf.GoGoProtos.goprotoStringer);
    registry.add(com.google.protobuf.GoGoProtos.moretags);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
